name: hive
version: 0.1.0.0
synopsis: Hive
license: BSD3
author: Mitchell Rosen
maintainer: mitchellwrosen@gmail.com
github: mitchellwrosen/hive
copyright: 2015-2016 Mitchell Rosen
category: Web

ghc-options: -Wall

default-extensions:
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - ViewPatterns

dependencies:
  - aeson
  - base
  - mitchell-prelude
  - text

library:
  source-dirs: src
  dependencies:
    - containers
    - extra
    - lens
    - free
    - mtl
    - semigroups
    - transformers
    - vector

executables:
  hive-local:
    source-dirs: app
    main: Hive/Impl/Console/LocalMain.hs
    other-modules:
      - Hive.Impl.Console.Player
    dependencies:
      - ansi-terminal
      - bytestring
      - haskeline
      - hive
      - lens
      - megaparsec
      - semigroups
      - transformers
      - vector

  hive-ws-server:
    source-dirs:
      - app
      - app/extra
    main: Hive/Impl/Console/WebSocketServerMain.hs
    dependencies:
      - async
      - bytestring
      - free
      - hive
      - http-types
      - lens
      - logging-effect
      - mmorph
      - monad-unlift
      - network
      - semigroups
      - transformers
      - vector
      - wai
      - wai-websockets
      - warp
      - websockets

  hive-ws-client:
    source-dirs:
      - app
      - app/extra
    main: Hive/Impl/Console/WebSocketClientMain.hs
    dependencies:
      - ansi-terminal
      - bytestring
      - free
      - haskeline
      - hive
      - lens
      - logging-effect
      - megaparsec
      - semigroups
      - transformers
      - vector
      - websockets

tests:
  hive-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hive
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
