resolver: ghc-8.0.1

packages:
- hive
- location:
    git: git@github.com:mitchellwrosen/mitchell-prelude
    commit: b11ee20
  extra-dep: true

extra-deps:
  - StateVar-1.1.0.4
  - adjunctions-4.3
  - aeson-0.11.2.0
  - async-2.1.0
  - attoparsec-0.13.0.2
  - base-orphans-0.5.4
  - bifunctors-5.3
  - comonad-5
  - contravariant-1.4
  - distributive-0.5.0.2
  - dlist-0.7.1.2
  - exceptions-0.8.2.1
  - extra-1.4.10
  - fail-4.9.0.0
  - free-4.12.4
  - hashable-1.2.4.0
  - kan-extensions-5.0.1
  - lens-4.14
  - microlens-0.4.5.0
  - microlens-ghc-0.4.5.0
  - microlens-mtl-0.1.8.0
  - microlens-platform-0.3.2.0
  - microlens-th-0.4.0.0
  - mtl-2.2.1
  - parallel-3.2.1.0
  - prelude-extras-0.4.0.3
  - primitive-0.6.1.0
  - profunctors-5.2
  - reflection-2.1.2
  - safe-exceptions-0.1.2.0
  - scientific-0.3.4.8
  - semigroupoids-5.1
  - semigroups-0.18.2
  - stm-2.4.4.1
  - syb-0.6
  - tagged-0.8.4
  - text-1.2.2.1
  - transformers-base-0.4.4
  - transformers-compat-0.5.1.4
  - unordered-containers-0.2.7.1
  - vector-0.11.0.0
  - void-0.7.1
