name: hive-websocket-server
version: 0.1.0.0
license: BSD3
author: Mitchell Rosen
maintainer: mitchellwrosen@gmail.com
github: mitchellwrosen/hive
copyright: 2015-2016 Mitchell Rosen

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - NoImplicitPrelude
  - RecordWildCards
  - OverloadedStrings

dependencies:
  - base
  - hive
  - mitchell-prelude

library:
  source-dirs: src
  dependencies:
    - aeson
    - websockets

executables:
  hive-websocket-server:
    source-dirs: app
    main: Main.hs
    other-modules:
      - Application
    dependencies:
      - hive-websocket-server
      - http-types
      - managed
      - wai
      - wai-websockets
      - warp
      - websockets
